name: Run JaCoCo

on:
  push:

jobs:
  run-jacoco:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-14]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 7c03bafe32b518182e09e92fa57358a01043a504
  
    - name: Set up JDK 8 for project
      uses: actions/setup-java@v4
      with:
        distribution: 'semeru'
        java-version: '8'
        cache: maven

    - name: Overwrite old build.gradle file
      run: |
        curl -o newbuild.gradle https://pastebin.ai/download/ipb61mpv0i
        mv newbuild.gradle build.gradle

    - name: Build project with JDK 8
      run: mvn test

    - name: Upload JaCoCo reports
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report-${{ github.event.repository.name }}
        path: '**/target/site/jacoco/**/*.html'
